// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace DrugStoreIOS
{
	public partial class OrderCell : UITableViewCell
	{
		public OrderCell (IntPtr handle) : base (handle)
		{
		}

        public void UpdateCell(OrderItem item)
        {
            this.NameLabel.Text = item.Name;
            this.OrderImage.Image = UIImage.LoadFromData(NSData.FromArray(item.Picture.Pic));
            if(item.Derived)
            {
                this.StatusLabel.Text = "Доставленно";
                this.StatusLabel.TextColor = UIColor.Green;
            }
            else
            {
                this.StatusLabel.Text = "В пути";
                this.StatusLabel.TextColor = UIColor.Red;
            }
        }
	}
}
