// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Text.RegularExpressions;
using System.IO;

using Foundation;
using AppKit;

namespace DrugStore
{
	public partial class EditViewController : NSViewController
	{
        public CatalogueItem item;
        public event EventHandler addOne;

		public EditViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            //блок инициализации полей
            NameField.StringValue = item.Name;
            BrandField.StringValue = item.Brand;
            PriceField.IntValue = item.Price;
            AvailableField.IntValue = item.Available;
            Desc.Value = item.Description;
            Imageview.Image = NSImage.FromStream(new MemoryStream(item.Image));

            //Кнопка отмены
            CancelButton.Activated += (sender, e) => DismissViewController(this);

            //Кнопка изменения с делегатом для обратного вызова в методе PrepareForsegue(адресата)
            EditedButton.Activated += (sender, e) => 
            {
                if (CheckExpressions())
                {
                    item.Name = NameField.StringValue;
                    item.Brand = BrandField.StringValue;
                    item.Price = PriceField.IntValue;
                    item.Available = AvailableField.IntValue;
                    item.Description = Desc.Value;

                    try
                    {
                        //Запрос к бд на изменение элемента
                        SqlClass.EditRow(item);

                        addOne(this, new EventArgs());
                        DismissViewController(this);
                    }
                    catch
                    {
                        (SqlClass.GetError("Не удалось добавить поле")).RunModal();
                    }

                }
                else
                    (SqlClass.GetError("Поля введены не верно")).RunModal();
                    
            };

            UploadButton.Activated += (sender, e) => 
            {
                NSOpenPanel openpanel = new NSOpenPanel();
                openpanel.AllowedFileTypes = new string[] {@"jpg"};
                openpanel.RunModal();
                Imageview.Image = new NSImage(openpanel.Url);
                if(openpanel.Url.Path != null)
                    item.Image = File.ReadAllBytes(openpanel.Url.Path);
            };
        }

        private bool CheckExpressions()
        {
            return (Regex.IsMatch(NameField.StringValue, @"^\w+") && Regex.IsMatch(BrandField.StringValue, @"^\w+") && Regex.IsMatch(PriceField.StringValue, @"^\d+$") && Regex.IsMatch(AvailableField.StringValue, @"^\d+$"));
        }
	}
}
