// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using Foundation;
using AppKit;

namespace DrugStore
{
	public partial class OrderViewControler : NSViewController
	{
        public List<OrderItem> orders = new List<OrderItem>();

		public OrderViewControler (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            try
            {
                orders = SqlClass.GetCollectionOrders();

                OrderSource sou = new OrderSource(orders);
                OrderView.DataSource = sou;
                OrderView.Delegate = new OrderDelegate(sou);
            }
            catch
            {
                //(SqlClass.GetError("Не удалось подключиться к БД")).RunModal();
            }

            DeleteButton.Activated += (sender, e) => 
            {
                if(OrderView.SelectedRow != -1)
                {
                    try
                    {
                        SqlClass.DeleteOrder(orders[(int)OrderView.SelectedRow]);

                        orders.RemoveAt((int)OrderView.SelectedRow);
                        OrderView.ReloadData();
                    }
                    catch
                    {
                        (SqlClass.GetError("Не удалось удалить из БД")).RunModal();
                    }
                }
            };

            RefreshButton.Activated += (sender, e) => 
            {
                try
                {
                    orders = SqlClass.GetCollectionOrders();

                    OrderSource sou = new OrderSource(orders);
                    OrderView.DataSource = sou;
                    OrderView.Delegate = new OrderDelegate(sou);
                }
                catch
                {
                    (SqlClass.GetError("Не удалось удалить из БД")).RunModal();
                }
            };
        }
	}
}
